(defconst my/configuration-path (expand-file-name "~/.emacs.d/configuration.org"))

(defun my/open-configuration ()
  "Opens emacs configuration."
  (interactive)
  (find-file my/configuration-path))

(defun my/load-configuration ()
  "Loads/reloads emacs configuration at runtime."
  (interactive)
  (org-babel-load-file my/configuration-path))

(my/load-configuration)

;; BELOW AUTOGENERATED STUFF

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (undo-tree vagrant yaml-mode synosaurus counsel-dash benchmark-init helpful which-key elfeed-org elfeed company-nixos-options nix-mode guix json-mode add-node-modules-path nodejs-repl eslintd-fix js2-mode flycheck-elm elm-mode emmet-mode web-mode reaper ox-reveal evil-org org-bullets evil-magit magit counsel-projectile flycheck company iedit treemacs-projectile treemacs-evil treemacs wgrep counsel expand-region rainbow-mode ibuffer-vc centered-cursor-mode evil-anzu anzu spaceline base16-theme general hydra evil-commentary evil-surround evil-collection evil esup smartparens session vlf gcmh auto-compile use-package)))
 '(session-use-package t nil (session)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
