#+TITLE: Emacs Configuration
#+AUTHOR: Andrey Koppel (akoppela)
#+EMAIL: akoppela@gmail.com

* Personal info.

  #+BEGIN_SRC emacs-lisp
    (setq user-full-name "Andrey Koppel")
    (setq user-mail-address "akoppela@gmail.com")
  #+END_SRC

* Package management.

** Initialize =package.el= and include Org, Gnu and Melpa package archives.

   #+BEGIN_SRC emacs-lisp
     (require 'package)
     (setq package-enable-at-startup nil)
     (setq package-archives '(("org" . "https://orgmode.org/elpa/")
                              ("gnu" . "https://elpa.gnu.org/packages/")
                              ("melpa" . "https://melpa.org/packages/")))
     (package-initialize)
   #+END_SRC

** TODO Fix a bug when it's not possible to download packages from GNU package archive.

   Should be fixed in Emacs 26.3

   #+BEGIN_SRC emacs-lisp
     (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
   #+END_SRC

** Make sure =use-package= is installed.

   #+BEGIN_SRC emacs-lisp
     (unless (package-installed-p 'use-package)
       (package-refresh-contents)
       (package-install 'use-package))
   #+END_SRC

** Initialize =use-package= and set it up to install the package if it's not available yet.

   #+BEGIN_SRC emacs-lisp
     (require 'use-package-ensure)
     (setq use-package-always-ensure t)
   #+END_SRC

** Always compile packages, and use the newest version available.

   #+BEGIN_SRC emacs-lisp
     (use-package auto-compile
       :config
       (auto-compile-on-load-mode 1))

     (setq load-prefer-newer t)
   #+END_SRC

* Defaults.

** Setup encoding to UTF-8.

   #+BEGIN_SRC emacs-lisp
     (setq coding-system-for-read 'utf-8)
     (setq coding-system-for-write 'utf-8)
   #+END_SRC

** Start with users home directory by default.

   #+BEGIN_SRC emacs-lisp
     (setq default-directory "~/")
   #+END_SRC

** Increase garbage collection treshold.

   This means GC runs less often, which speeds up some operations.

   #+BEGIN_SRC emacs-lisp
     (setq gc-cons-treshold 20000000)
   #+END_SRC

** Delete trailing whitespace everytime buffer is saved.

   #+BEGIN_SRC emacs-lisp
     (add-hook 'before-save-hook 'delete-trailing-whitespace)
   #+END_SRC

** Always follow symlinks when opening a file.

   #+BEGIN_SRC emacs-lisp
     (setq vc-follow-symlinks t)
   #+END_SRC

** Make sure sentenses does not have two spaces after periods.

   #+BEGIN_SRC emacs-lisp
     (setq sentense-end-double-space nil)
   #+END_SRC

** Ask before closing Emacs.

   #+BEGIN_SRC emacs-lisp
     (setq confirm-kill-emacs 'y-or-n-p)
   #+END_SRC

** Set backup files directory.

   #+BEGIN_SRC emacs-lisp
     (setq backup-directory-alist '(("." . "~/.emacs.d/backups")))
   #+END_SRC

** Set auto save files directory.

   #+BEGIN_SRC emacs-lisp
     (setq auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-save-list/" t)))
   #+END_SRC

** Shorten yes/no answers.

   #+BEGIN_SRC emacs-lisp
     (defalias 'yes-or-no-p 'y-or-n-p)
   #+END_SRC

** Open large files with =vlf=.

   #+BEGIN_SRC emacs-lisp
     (use-package vlf
       :config
       (require 'vlf-setup))
   #+END_SRC

** Do not add newline at the end of a file.

   #+BEGIN_SRC emacs-lisp
     (setq require-final-newline nil)
     (setq mode-require-final-newline nil)
   #+END_SRC

** Set =eww= as default browser.

   #+BEGIN_SRC emacs-lisp
     (setq browse-url-browser-function 'eww-browse-url)
   #+END_SRC

* Appearance.

** Hide default Emacs screen.

   #+BEGIN_SRC emacs-lisp
     (setq inhibit-startup-screen t)
   #+END_SRC

** Change default scratch message.

   #+BEGIN_SRC emacs-lisp
     (setq initial-scratch-message (concat "Welcome in Emacs\nStartup time: " (emacs-init-time)))
   #+END_SRC

** Enable custom theme.

   #+BEGIN_SRC emacs-lisp
     (use-package base16-theme
       :custom
       (base16-theme-256-color-source 'colors)
       :init
       (add-to-list 'custom-theme-load-path "~/.emacs.d/my/theme")
       :config
       (load-theme 'base16-my-theme t))
   #+END_SRC

** =mode-line= specific.

*** Initialize =spaceline=.

    #+BEGIN_SRC emacs-lisp
      (use-package spaceline
        :config
        (require 'spaceline-config)
        (spaceline-spacemacs-theme))
    #+END_SRC

*** Change =mode-line= highlight color based on evil mode.

    #+BEGIN_SRC emacs-lisp
      (setq spaceline-highlight-face-func 'spaceline-highlight-face-evil-state)
    #+END_SRC

*** Hide minor modes.

    #+BEGIN_SRC emacs-lisp
      (spaceline-toggle-minor-modes-off)
    #+END_SRC

*** Show full names for evil state.

    #+BEGIN_SRC emacs-lisp
      (setq evil-normal-state-tag "N")
      (setq evil-insert-state-tag "I")
      (setq evil-visual-state-tag "V")
      (setq evil-replace-state-tag "R")
      (setq evil-operator-state-tag "O")
      (setq evil-motion-state-tag "M")
      (setq evil-emacs-state-tag "E")
    #+END_SRC

*** Show date and time.

    #+BEGIN_SRC emacs-lisp
      (defun padDateNumber (stringNumber)
        (format "%02d" (string-to-number stringNumber)))

      (setq display-time-string-forms
            '(24-hours ":" minutes " " dayname " "  (padDateNumber day) "/" (padDateNumber month) "/" year))

      (display-time-mode 1)
    #+END_SRC

** Hide menu and tool bars.

   #+BEGIN_SRC emacs-lisp
     (tool-bar-mode 0)
     (menu-bar-mode 0)
   #+END_SRC

** Enable current line highlighting.

   #+BEGIN_SRC emacs-lisp
     (global-hl-line-mode 1)
   #+END_SRC

** Turn on syntax highlighting whenever possible.

   #+BEGIN_SRC emacs-lisp
     (global-font-lock-mode 1)
   #+END_SRC

** Visually indicate matching parentheses.

   #+BEGIN_SRC emacs-lisp
     (show-paren-mode 1)
     (setq show-paren-delay 0.0)
   #+END_SRC

** Flash screen on invalid operation.

   #+BEGIN_SRC emacs-lisp
     (setq visible-bell t)
   #+END_SRC

** Display visual line numbers.

   Visual lines are relative screen lines.

   #+BEGIN_SRC emacs-lisp
     (global-display-line-numbers-mode)
     (setq display-line-numbers-type 'visual)
     (setq display-line-numbers-width-start t)
   #+END_SRC

** Always indent with spaces

   #+BEGIN_SRC emacs-lisp
     (setq-default indent-tabs-mode nil)
   #+END_SRC

** Use 4 spaces for tabs.

   #+BEGIN_SRC emacs-lisp
     (setq-default tab-width 4)
   #+END_SRC

** Smooth scroll.

   #+BEGIN_SRC emacs-lisp
     (setq scroll-conservatively 100)
   #+END_SRC

** Center cursor vertically.

   #+BEGIN_SRC emacs-lisp
     (use-package centered-cursor-mode
       :config
       (global-centered-cursor-mode 1))
   #+END_SRC

** Add color background for hexadecimal strings.

   #+BEGIN_SRC emacs-lisp
     (use-package rainbow-mode
       :config (add-hook 'prog-mode-hook 'rainbow-mode))
   #+END_SRC

* Keybindings.

** =evil= provides =vi= keybindings.

*** Initialize =evil=.

    #+BEGIN_SRC emacs-lisp
      (use-package evil
        :custom
        (evil-want-C-i-jump nil)
        (evil-want-integration t)
        (evil-want-keybinding nil)
        :init
        :config
        (evil-mode 1))
    #+END_SRC

*** Enable =evil-collection=.

    #+BEGIN_SRC emacs-lisp
      (use-package evil-collection
        :after evil
        :custom
        (evil-collection-setup-minibuffer t)
        (evil-collection-outline-bind-tab-p nil)
        :config
        (evil-collection-init))
    #+END_SRC

*** Enable =evil-surround=.

    #+BEGIN_SRC emacs-lisp
      (use-package evil-surround
        :after evil-collection
        :config
        (global-evil-surround-mode 1))
    #+END_SRC

*** Enable =evil-org=.

    #+BEGIN_SRC emacs-lisp
      (use-package evil-org
        :after (evil-collection org)
        :config
        (add-hook 'org-mode-hook 'evil-org-mode)
        (add-hook 'evil-org-mode-hook (lambda () (evil-org-set-key-theme)))
        (require 'evil-org-agenda)
        (evil-org-agenda-set-keys))
    #+END_SRC

*** Enable =evil-commentary=.

    #+BEGIN_SRC emacs-lisp
      (use-package evil-commentary
        :after evil-collection
        :config
        (evil-commentary-mode 1))
    #+END_SRC

** =general= makes it easier to assign keybindings.

*** Initialize.

    #+BEGIN_SRC emacs-lisp
      (use-package general
        :config
        (general-create-definer leader-def
          :states '(normal visual insert motion emacs)
          :keymaps 'override
          :prefix "SPC"
          :non-normal-prefix "C-SPC")
        (general-create-definer major-def
          :states '(normal visual motion emacs)
          :prefix ","
          :non-normal-prefix "C-,"))
    #+END_SRC

*** Main menu.

    #+BEGIN_SRC emacs-lisp
      (leader-def
        "" nil
        "SPC" '(counsel-M-x :which-key "M-x")
        "/" '(counsel-projectile-git-grep :which-key "find in project"))
    #+END_SRC

*** Buffer.

    #+BEGIN_SRC emacs-lisp
      (leader-def
        "b" '(:ignore t :which-key "buffer")
        "b b" '(ivy-switch-buffer :which-key "switch")
        "b d" '(kill-current-buffer :which-key "delete")
        "b x" '(kill-buffer-and-window :which-key "delete with window")
        "b r" '(rename-buffer :which-key "rename"))
    #+END_SRC

*** Window.

    #+BEGIN_SRC emacs-lisp
      (leader-def
        "w" '(:ignore t :which-key "window")
        "w TAB" '(other-window :which-key "next")
        "w d" '(delete-window :which-key "delete")
        "w D" '(delete-other-windows :which-key "delete other")

        "w s" '(:ignore t :which-key "split")
        "w s h" '(split-window-below :which-key "split horizontally")
        "w s v" '(split-window-right :which-key "split vertically"))
    #+END_SRC

*** File.

**** Helper functions.

     #+BEGIN_SRC emacs-lisp
       (defun my/delete-file-and-buffer ()
         "Kill the current buffer and delete the file it's visiting."
         (interactive)
         (let ((filename (buffer-file-name)))
           (if filename
               (if (vc-backend filename)
                   (vc-delete-file filename)
                 (progn (delete-file filename)
                        (message "Deleted file %s." filename)
                        (kill-buffer)))
             (message "Can't delete file."))))
     #+END_SRC

**** Bindings.

     #+BEGIN_SRC emacs-lisp
       (leader-def
         "f" '(:ignore t :which-key "file")
         "f f" '(counsel-find-file :which-key "find")
         "f s" '(save-buffer :which-key "save")
         "f r" '(rename-file :which-key "rename")
         "f d" '(my/delete-file-and-buffer :which-key "delete")

         "f e" '(:ignore t :which-key "emacs")
         "f e c" '(my/open-configuration :which-key "configuration")
         "f e r" '(my/load-configuration :which-key "reload configuration"))
     #+END_SRC

*** Project.

    #+BEGIN_SRC emacs-lisp
      (leader-def
        "p" '(:ignore t :which-key "project")
        "p f" '(counsel-projectile-find-file :which-key "find file")
        "p p" '(counsel-projectile-switch-project :which-key "switch")
        "p b" '(counsel-projectile-switch-to-buffer :which-key "buffer")
        "p t" '(treemacs :which-key "treemacs"))
    #+END_SRC

*** Application.

    #+BEGIN_SRC emacs-lisp
      (leader-def
        "a" '(:ignore t :which-key "application"))
    #+END_SRC

*** Search.

    #+BEGIN_SRC emacs-lisp
      (leader-def
        "s" '(:ignore t :which-key "search")
        "s s" '(swiper-isearch :which-key "buffer")
        "s S" '(swiper-isearch-thing-at-point :which-key "buffer with thing at point")
        "s b" '(eww-search-words :which-key "browser")
        "s i" '(imenu :which-key "imenu"))
    #+END_SRC

*** Error.

    #+BEGIN_SRC emacs-lisp
      (leader-def
        "e" '(:ignore t :which-key "error")
        "e n" '(flycheck-next-error :which-key "next")
        "e p" '(flycheck-previous-error :which-key "previous")
        "e l" '(flycheck-list-errors :which-key "list"))
    #+END_SRC

*** Git.

    #+BEGIN_SRC emacs-lisp
      (leader-def
        "g" '(:ignore t :which-key "git")
        "g s" '(magit-status :which-key "status")
        "g b" '(magit-blame :which-key "blame"))
    #+END_SRC

*** Narrow.

    #+BEGIN_SRC emacs-lisp
      (leader-def
        "n" '(:ignore t :which-key "narrow")
        "n f" '(narrow-to-defun :which-key "function")
        "n r" '(narrow-to-region :which-key "region")
        "n p" '(narrow-to-page :which-key "page")
        "n w" '(widen :which-key "widen"))
    #+END_SRC

*** Jump.

    #+BEGIN_SRC emacs-lisp
      (leader-def
        "j" '(:ignore t :which-key "jump")
        "j w" '(avy-goto-word-1 :which-key "word"))
    #+END_SRC

*** Help.

    #+BEGIN_SRC emacs-lisp
      (leader-def
        "h" '(:ignore t :which-key "help")
        "h f" '(counsel-describe-function :which-key "describe function")
        "h v" '(counsel-describe-variable :which-key "describe variable")
        "h k" '(helpful-key :which-key "describe key")
        "h b" '(benchmark-init/show-durations-tabulated :which-key "benchmark emacs initialization"))
    #+END_SRC

*** Quit.

    #+BEGIN_SRC emacs-lisp
      (leader-def
        "q" '(:ignore t :which-key "quit")
        "q q" '(save-buffers-kill-terminal :which-key "client")
        "q Q" '(save-buffers-kill-emacs :which-key "server"))
    #+END_SRC

* Navigation and search.

** =counsel= completion framework.

   #+BEGIN_SRC emacs-lisp
     (use-package counsel
       :config
       (ivy-mode 1)
       (major-def
         :keymaps 'ivy-minibuffer-map
         "o" '(ivy-occur :which-key "occur")))
   #+END_SRC

** =multiple-cursors=.

   #+BEGIN_SRC emacs-lisp
     (use-package multiple-cursors)
   #+END_SRC

** =wgrep= to edit search.

   #+BEGIN_SRC emacs-lisp
     (use-package wgrep)
   #+END_SRC

** =treemacs= file explorer.

   #+BEGIN_SRC emacs-lisp
     (use-package treemacs)

     (use-package treemacs-evil
       :after (treemacs evil-collection))

     (use-package treemacs-projectile
       :after (treemacs projectile))
   #+END_SRC

** =iedit= to edit multiple regions simultaneously.

   #+BEGIN_SRC emacs-lisp
     (use-package iedit)
   #+END_SRC

* Project management.

** =projectile=.

   #+BEGIN_SRC emacs-lisp
     (use-package projectile
       :config
       (projectile-mode 1)
       (setq projectile-completion-system 'ivy))

     (use-package counsel-projectile
       :after (projectile counsel)
       :config
       (counsel-projectile-mode 1))
   #+END_SRC

** =magit= for Git related stuff.

   #+BEGIN_SRC emacs-lisp
     (defun my/magit-clean-quit ()
       "Restore window configuration and kill all Magit buffers."
       (interactive)
       (let ((buffers (magit-mode-get-buffers)))
         (magit-restore-window-configuration)
         (mapc #'kill-buffer buffers)))

     (use-package magit
       :config
       (general-def
         :states 'normal
         :keymaps 'magit-status-mode-map
         "q" 'my/magit-clean-quit))

     (use-package evil-magit
       :after (evil-collection magit))
   #+END_SRC

* Document content management.

** =company= enables auto-completion.

   #+BEGIN_SRC emacs-lisp
     (use-package company
       :custom
       (company-idle-delay 0)
       (company-minimum-prefix-length 2)
       (company-dabbrev-downcase nil))

     (add-hook 'after-init-hook 'global-company-mode)
   #+END_SRC

** =flycheck= checks syntax.

   #+BEGIN_SRC emacs-lisp
     (use-package flycheck)
   #+END_SRC

** =flyspell= checks spelling.

   #+BEGIN_SRC emacs-lisp
     (use-package flyspell
       :config
       (add-hook 'text-mode-hook 'flyspell-mode)
       (add-hook 'prog-mode-hook 'flyspell-prog-mode)
       (add-hook 'org-mode-hook 'flyspell-mode)
       (add-hook 'git-commit-mode-hook 'flyspell-mode))
   #+END_SRC

* Task management.

  The killer =org-mode=.

** Keybindings.

   #+BEGIN_SRC emacs-lisp
     (defun my/open-notes ()
       "Opens my notes."
       (interactive)
       (find-file (expand-file-name "~/org/notes.org")))

     (leader-def
       "a n" '(my/open-notes :which-key "notes"))

     (major-def
       :keymaps 'org-mode-map
       "'" '(org-edit-special :which-key "src editor")

       "d" '(:ignore t :which-key "date")
       "d s" '(org-schedule :which-key "schedule")

       "s" '(:ignore t :which-key "subtree")
       "s r" '(org-refile :which-key "refile"))
   #+END_SRC

** Show bullets instead of stars.

   #+BEGIN_SRC emacs-lisp
     (use-package org-bullets
       :after org
       :init
       (add-hook 'org-mode-hook 'org-bullets-mode))
   #+END_SRC

** Change collapsed subtree symbol.

   #+BEGIN_SRC emacs-lisp
     (setq org-ellipsis " ↴")
   #+END_SRC

** Make TAB act natively for code blocks.

   #+BEGIN_SRC emacs-lisp
     (setq org-src-tab-acts-natively t)
   #+END_SRC

** Custom TODO keywords.

   #+BEGIN_SRC emacs-lisp
     (setq org-todo-keywords '((sequence "TODO" "PROG" "|" "DONE")))
     (setq org-todo-keyword-faces
           `(("TODO" . (:background ,base16-my-theme-base01 :foreground ,base16-my-theme-base08 :weight bold))
             ("PROG" . (:background ,base16-my-theme-base01 :foreground ,base16-my-theme-base0D :weight bold))
             ("DONE" . (:background ,base16-my-theme-base01 :foreground ,base16-my-theme-base0B :weight bold))))
     (setq org-log-done t)
   #+END_SRC

** Agenda files.

   #+BEGIN_SRC emacs-lisp
      (setq org-agenda-files (list "~/org/notes.org"))
   #+END_SRC

** Better =org-refile=.

   #+BEGIN_SRC emacs-lisp
     (setq org-refile-targets '((org-agenda-files :maxlevel . 2) (my/configuration-path :maxlevel . 2)))
     (setq org-refile-use-outline-path 'file)
     (setq org-outline-path-complete-in-steps nil)
     (setq org-refile-allow-creating-parent-nodes 'confirm)
   #+END_SRC

* Time management.

** =harvest=.

*** Initialize.

    #+BEGIN_SRC emacs-lisp
      (use-package reaper
        :custom
        (reaper-api-key (getenv "HARVEST_API_KEY"))
        (reaper-account-id (getenv "HARVEST_ACCOUNT_ID")))
    #+END_SRC

*** Helper functions.

**** Overriden =reaper-refresh-entries=.

     #+BEGIN_SRC emacs-lisp
       (defun reaper-refresh-entries ()
         "Fetch time-entries from Harvest."
         (reaper--check-credentials)
         (reaper-with-buffer
          (message "Refreshing data from Harvest...")
          (let* ((response-entries
                  (reaper-alist-get '(time_entries)
                                    (reaper-api "GET"
                                                (format "time_entries?from=%s&to=%s"  reaper-date reaper-date)
                                                nil
                                                "Refreshed cache of daily entries")))
                 (request-time (current-time)))
            (setq reaper-running-timer nil)
            (setq reaper-timeentries
                  (mapcar
                   (lambda (entry)
                     (when (reaper-alist-get '(is_running) entry)
                       (setq reaper-running-timer (reaper-alist-get '(id) entry)))
                     (cons (reaper-alist-get '(id) entry)
                           (list
                            (cons :id (reaper-alist-get '(id) entry))
                            (cons :project_id (reaper-alist-get '(project id) entry))
                            (cons :project (reaper-alist-get '(project name) entry))
                            (cons :task_id (reaper-alist-get '(task id) entry))
                            (cons :task (reaper-alist-get '(task name) entry))
                            (cons :is_running (reaper-alist-get '(is_running) entry))
                            (cons :hours (reaper-alist-get '(hours) entry))
                            (cons :started_time (reaper-alist-get '(started_time) entry))
                            (cons :ended_time (reaper-alist-get '(ended_time) entry))
                            (cons :notes (let ((notes (reaper-alist-get '(notes) entry)))
                                           (if notes (decode-coding-string notes 'utf-8) ""))))))
                   ;; API returns newest entry first. Simply reverse the list.
                   (reverse response-entries)))
            (setq reaper-fetch-time request-time))))
     #+END_SRC

**** Overriden =reaper-edit-entry-time=.

     #+BEGIN_SRC emacs-lisp
       (defun reaper-edit-entry-time ()
         "Edit start/end time of entry at point."
         (interactive)
         (let* ((entry-id (tabulated-list-get-id))
                (entry (assoc entry-id reaper-timeentries))
                (start-time (cdr (assoc :started_time entry)))
                (new-start-time (read-string "New start time: " start-time))
                (end-time (cdr (assoc :ended_time entry)))
                (new-end-time (read-string "New end time: " end-time))
                (harvest-payload (make-hash-table :test 'equal)))
           (puthash "started_time" new-start-time harvest-payload)
           (puthash "ended_time" new-end-time harvest-payload)
           (reaper-api "PATCH" (format "time_entries/%s" entry-id) harvest-payload "Updated entry")
           (reaper-refresh)))
     #+END_SRC

*** Keybindings.

    #+BEGIN_SRC emacs-lisp
      (leader-def
        "a h" '(reaper :which-key "harvest"))

      (general-def
        :states 'normal
        :keymaps 'reaper-mode-map
        "q" 'kill-buffer-and-window)

      (major-def
        :keymaps 'reaper-mode-map
        "r" '(reaper-refresh :which-key "refresh")
        "d" '(reaper-goto-date :which-key "date")
        "s" '(reaper-start-timer :which-key "start timer")
        "S" '(reaper-stop-timer :which-key "stop timer")
        "n" '(reaper-start-new-timer :which-key "new timer")
        "e" '(reaper-edit-entry-time :which-key "edit time")
        "E" '(reaper-edit-entry :which-key "edit entry")
        "x" '(reaper-delete-entry :which-key "delete"))
    #+END_SRC

* Programming languages.

** =html=.

   #+BEGIN_SRC emacs-lisp
     (use-package web-mode
       :mode
       ("\\.html?\\'" . web-mode)
       ("\\.php\\'" . web-mode))

     (use-package emmet-mode
       :config
       (emmet-preview-mode 0)
       (add-hook 'sgml-mode-hook 'emmet-mode)
       (add-hook 'css-mode-hook 'emmet-mode)

       (general-def
         :definer 'minor-mode
         :states 'insert
         :keymaps 'emmet-mode
         "TAB" 'emmet-expand-line))
   #+END_SRC

** =elm=.

   #+BEGIN_SRC emacs-lisp
     (use-package elm-mode
       :custom
       (elm-package-json "elm.json")
       (elm-mode-generate-tags t)
       :config
       (add-hook 'elm-mode-hook 'elm-format-on-save-mode)
       (add-hook 'elm-mode-hook 'flycheck-mode))

     (use-package flycheck-elm
       :after (flycheck elm-mode)
       :config
       (add-hook 'flycheck-mode-hook 'flycheck-elm-setup))
   #+END_SRC

** =javascript=.

   #+BEGIN_SRC emacs-lisp
     (use-package js2-mode
       :mode ("\\.js\\'" . js2-mode)
       :config
       (add-hook 'js2-mode-hook 'js2-imenu-extras-mode)
       (add-hook 'js2-mode-hook 'flycheck-mode))
   #+END_SRC

** =json=.

   #+BEGIN_SRC emacs-lisp
     (use-package json-mode
       :config
       (major-def
         :keymaps 'json-mode-map
         "p" '(json-mode-show-path :which-key "path")))
   #+END_SRC

* Help.

** =which-key= shows all available keybindings in a popup.

   #+BEGIN_SRC emacs-lisp
     (use-package which-key
       :config
       (which-key-mode 1))
   #+END_SRC

** =helpful= provides *Help* buffer on steroids.

   #+BEGIN_SRC emacs-lisp
     (use-package helpful
       :custom
       (counsel-describe-function-function #'helpful-callable)
       (counsel-describe-variable-function #'helpful-variable)
       :config
       (general-def
         :states 'normal
         :keymaps 'helpful-mode-map
         "q" 'kill-buffer-and-window))
   #+END_SRC

** Benchmark emacs initialization.

   #+BEGIN_SRC emacs-lisp
     (use-package benchmark-init
       :config
       (add-hook 'after-init-hook 'benchmark-init/deactivate))
   #+END_SRC

* News.

** =elfeed= RSS reader.

   #+BEGIN_SRC emacs-lisp
     (use-package elfeed
       :config
       (leader-def
         "a e" 'elfeed)
       (major-def
         :keymaps 'elfeed-search-mode-map
         "u" '(elfeed-update :which-key "update")))

     (use-package elfeed-org
       :after (elfeed org)
       :custom
       (rmh-elfeed-org-files (list "~/org/rss.org"))
       :config
       (elfeed-org))
   #+END_SRC

* Helper functions.

** Exec npm command.

   #+BEGIN_SRC emacs-lisp
     (defun my/conta-exec-npm (root-folder cmd-name)
       "Starts eshell buffer with given name, enters Conta's frontend folder and executes given npm command."
       (progn
         (if (get-buffer cmd-name)
             (switch-to-buffer cmd-name)
           (progn
             (eshell)
             (rename-buffer cmd-name)
             (insert "cd " root-folder " && npm run " cmd-name)
             (eshell-send-input)))))
   #+END_SRC

* Conta.

** Helper functions.

*** Frontend root folder.

    #+BEGIN_SRC emacs-lisp
      (defconst my/conta-frontend-root "~/contadev/front-end/")
    #+END_SRC

*** Serve frontend.

    #+BEGIN_SRC emacs-lisp
      (defun my/conta-frontend-serve ()
        "Starts Conta's frontend development server."
        (interactive)
        (my/conta-exec-npm my/conta-frontend-root "dev:watch"))
    #+END_SRC

*** Run frontend JS tests.

    #+BEGIN_SRC emacs-lisp
      (defun my/conta-frontend-js-tests ()
        "Runs Conta's frontend JS unit tests command."
        (interactive)
        (my/conta-exec-npm my/conta-frontend-root "tests:unit"))
    #+END_SRC

*** Run frontend JS tests coverage.

    #+BEGIN_SRC emacs-lisp
      (defun my/conta-frontend-js-tests-coverage ()
        "Runs Conta's frontend JS unit tests coverage command."
        (interactive)
        (my/conta-exec-npm my/conta-frontend-root "tests:unit:enforce"))
    #+END_SRC

*** Clean elm stuff.

    #+BEGIN_SRC emacs-lisp
      (defun my/conta-frontend-elm-clean-stuff ()
        "Cleans Conta's frontend Elm stuff."
        (interactive)
        (my/conta-exec-npm my/conta-frontend-root "elm:clean:stuff"))
    #+END_SRC

*** Update frontend.

    #+BEGIN_SRC emacs-lisp
      (defun my/conta-frontend-update ()
        "Updates Conta's frontend to the latest version."
        (interactive)
        (my/conta-exec-npm my/conta-frontend-root "update"))
    #+END_SRC

** Keybindings.

   #+BEGIN_SRC emacs-lisp
     (leader-def
       "a c" '(:ignore t :which-key "conta")

       "a c u" '(my/conta-frontend-update :which-key "update")

       "a c s" '(:ignore t :which-key "serve")
       "a c s f" '(my/conta-frontend-serve :which-key "frontend")

       "a c e" '(:ignore t :which-key "elm")
       "a c e c" '(my/conta-frontend-elm-clean-stuff :which-key "clean stuff")

       "a c j" '(:ignore t :which-key "javascript")
       "a c j t" '(my/conta-frontend-js-tests :which-key "test")
       "a c j c" '(my/conta-frontend-js-tests-coverage :which-key "coverage"))
   #+END_SRC

* Moontells.

** Helper functions.

*** Root folder.

    #+BEGIN_SRC emacs-lisp
      (defconst my/moontells-root "~/moontells/")
    #+END_SRC

*** Serve mobile app.

    #+BEGIN_SRC emacs-lisp
      (defun my/moontells-mobile-serve ()
        "Starts Moontells's mobile app development server."
        (interactive)
        (my/conta-exec-npm my/moontells-root "start:app"))
    #+END_SRC

** Keybindings.

   #+BEGIN_SRC emacs-lisp
     (leader-def
       "a m" '(:ignore t :which-key "moontells")

       "a m m" '(:ignore t :which-key "mobile")
       "a m m s" '(my/moontells-mobile-serve :which-key "serve"))
   #+END_SRC

* The End!
