(defconst akoppela/configuration-path (expand-file-name "~/.emacs.d/configuration.org"))

(defun akoppela/open-configuration ()
  "Opens emacs configuration."
  (interactive)
  (find-file akoppela/configuration-path))

(defun akoppela/load-configuration ()
  "Loads/reloads emacs configuration at runtime."
  (interactive)
  (org-babel-load-file akoppela/configuration-path))

(akoppela/load-configuration)

;; BELOW AUTOGENERATED STUFF

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (ag symon evil-magit magit which-key use-package spaceline evil-surround evil-org evil-commentary cycle-themes base16-theme auto-compile))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
